@id=43b4c6e4-c260-4b3a-aff7-09d9c40f05e1
PUT http://localhost:5140/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Americano",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
    "Sweet": ["Cookie"]
}